; PlatformIO Project Configuration File for Face Detection on Arduino Nano 33 BLE
[env:arduino]
platform = nordicnrf52
board = nano33ble
framework = arduino
lib_deps =
    https://github.com/spaziochirale/ArduTFLite.git
    ArduCAM

[platformio]
default_envs = arduino
