/*
  Gesture Detection — Project 4
  ==============================
  Captures 320x240 RGB565 frames from an ArduCAM OV2640, downsamples to
  96x96 grayscale, and runs int8 TFLite Micro inference to classify one of
  5 hand gestures (or report no gesture if confidence is too low).

  Classes (index order matches training label_map.json):
    0: call   1: dislike   2: like   3: mute   4: ok

  Hardware:
    - Arduino Nano 33 BLE Sense
    - ArduCAM OV2640 Mini 2MP  (SPI, CS pin → D10)

  Libraries (install via Arduino Library Manager):
    - ArduCAM
    - Chirale_TensorFlowLite

  Usage:
    Open Serial Monitor at 115200 baud.
    Send the character 'c' to trigger a capture + inference.
*/

#include <Wire.h>
#include <SPI.h>
#include <ArduCAM.h>

#undef swap   // ArduCAM defines swap(), conflicts with STL
#include <Chirale_TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/micro/system_setup.h>
#include <tensorflow/lite/schema/schema_generated.h>

// Generated by train_cnn_model.py — place in the same sketch folder
#include "model_data.h"

// ── Config ────────────────────────────────────────────────────────────────────

#define CS_PIN      10      // ArduCAM chip-select pin
#define CAM_COLS   320      // OV2640 capture width  (pixels)
#define CAM_ROWS   240      // OV2640 capture height (pixels)
#define IMG_COLS    96      // Model input width
#define IMG_ROWS    96      // Model input height
#define NUM_CLASSES  5

// Minimum dequantized softmax score to report a detection.
// Below this threshold the result is printed as "NO GESTURE DETECTED".
const float CONFIDENCE_THRESHOLD = 0.60f;

const char* CLASS_NAMES[NUM_CLASSES] = {
    "call", "dislike", "like", "mute", "ok"
};

// ── TFLite globals ────────────────────────────────────────────────────────────

// Tensor arena holds all intermediate activations during inference.
// 100 KB is sufficient for this model at 96x96 int8; raise if
// AllocateTensors() fails.
constexpr int kTensorArenaSize = 100 * 1024;
alignas(16) uint8_t tensor_arena[kTensorArenaSize];

const tflite::Model*      tfl_model   = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor*             tfl_input   = nullptr;
TfLiteTensor*             tfl_output  = nullptr;

// ── Camera ────────────────────────────────────────────────────────────────────

ArduCAM cam(OV2640, CS_PIN);

// Optional debug buffer — stores the downsampled grayscale image so it can
// be dumped over Serial for visualisation. Comment out to save RAM.
uint8_t debug_image[IMG_ROWS * IMG_COLS];

// ── captureAndFillTensor ──────────────────────────────────────────────────────
//
// Reads one 320x240 RGB565 frame from the ArduCAM FIFO over SPI, performs
// nearest-neighbour downsampling to 96x96, converts to grayscale using
// BT.601 luminance coefficients, then quantises the float pixel value into
// the int8 range expected by the model's input tensor.
//
void captureAndFillTensor() {
    uint8_t row_buf[CAM_COLS * 2];   // one row: 320 pixels × 2 bytes = 640 B

    cam.flush_fifo();
    cam.clear_fifo_flag();
    cam.start_capture();
    while (!cam.get_bit(ARDUCHIP_TRIG, CAP_DONE_MASK)) { delay(1); }

    Serial.print("FIFO length: ");
    Serial.println(cam.read_fifo_length());

    // Cache quantisation params — same for every pixel in the input tensor
    float   in_scale = tfl_input->params.scale;
    int32_t in_zp    = tfl_input->params.zero_point;

    cam.CS_LOW();
    SPI.transfer(BURST_FIFO_READ);

    int prev_out_row = -1;

    for (int src_row = 0; src_row < CAM_ROWS; src_row++) {
        // Read the full row from FIFO — must be done even for skipped rows
        for (int i = 0; i < (int)sizeof(row_buf); i++) {
            row_buf[i] = SPI.transfer(0x00);
        }

        // Map this source row to an output row (floor nearest-neighbour).
        // 240 source rows → 96 output rows (ratio 2.5).
        // Multiple source rows map to the same output row; only process the
        // first one (when out_row changes).
        int out_row = src_row * IMG_ROWS / CAM_ROWS;
        if (out_row == prev_out_row) continue;
        prev_out_row = out_row;

        for (int out_col = 0; out_col < IMG_COLS; out_col++) {
            // Nearest-neighbour column mapping: 320 → 96
            int src_col = out_col * CAM_COLS / IMG_COLS;
            if (src_col >= CAM_COLS) src_col = CAM_COLS - 1;

            // Unpack RGB565 big-endian
            uint16_t px = ((uint16_t)row_buf[src_col * 2]     << 8)
                        |  (uint16_t)row_buf[src_col * 2 + 1];

            // Expand to 8-bit channels
            uint8_t r = ((px >> 11) & 0x1F) << 3;
            uint8_t g = ((px >>  5) & 0x3F) << 2;
            uint8_t b = ( px        & 0x1F) << 3;

            // BT.601 luminance (integer arithmetic, no float division here)
            uint8_t gray = (uint8_t)((77 * (uint16_t)r
                                    + 150 * (uint16_t)g
                                    +  29 * (uint16_t)b) >> 8);

            // Store debug image (optional)
            debug_image[out_row * IMG_COLS + out_col] = gray;

            // Quantise to int8:
            //   training normalisation  : float_val = gray / 255.0
            //   int8 quantisation       : q = round(float_val / scale) + zero_point
            int32_t q = (int32_t)roundf((float)gray / (255.0f * in_scale))
                        + in_zp;
            if (q < -128) q = -128;
            if (q >  127) q =  127;
            tfl_input->data.int8[out_row * IMG_COLS + out_col] = (int8_t)q;
        }
    }

    cam.CS_HIGH();
}

// ── setup ─────────────────────────────────────────────────────────────────────

void setup() {
    Serial.begin(115200);
    while (!Serial) { ; }
    Serial.println("=== Gesture Detector — Project 4 ===");

    // ── Camera init ──────────────────────────────────────────────────────────
    Wire.begin();
    SPI.begin();
    pinMode(CS_PIN, OUTPUT);
    digitalWrite(CS_PIN, HIGH);

    // Verify SPI bus
    cam.write_reg(ARDUCHIP_TEST1, 0x55);
    if (cam.read_reg(ARDUCHIP_TEST1) != 0x55) {
        Serial.println("ERROR: ArduCAM SPI failure!"); while (1);
    }

    // Verify OV2640 sensor ID (CHIPID_HIGH = 0x26)
    uint8_t vid, pid;
    cam.wrSensorReg8_8(0xff, 0x01);
    cam.rdSensorReg8_8(0x0A, &vid);
    cam.rdSensorReg8_8(0x0B, &pid);
    if (vid != 0x26) {
        Serial.println("ERROR: OV2640 not detected!"); while (1);
    }
    Serial.print("OV2640 ID: 0x");
    Serial.println(((uint16_t)vid << 8) | pid, HEX);

    cam.set_format(BMP);
    cam.InitCAM();
    cam.set_bit(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);
    cam.clear_fifo_flag();

    // Override to raw RGB565 output (bypass OV2640 internal JPEG engine)
    cam.wrSensorReg8_8(0xFF, 0x00);  // select DSP register bank
    cam.wrSensorReg8_8(0xDA, 0x08);  // IMAGE_MODE: non-compressed RGB565

    // Auto exposure and auto gain control
    cam.wrSensorReg8_8(0xFF, 0x01);  // select sensor register bank
    cam.wrSensorReg8_8(0x13, 0x05);  // COM8: AEC (bit0) + AGC (bit2)
    cam.wrSensorReg8_8(0x14, 0x48);  // COM9: AGC gain ceiling = 32x

    Serial.println("Camera ready (320x240 RGB565)");

    // ── TFLite Micro init ────────────────────────────────────────────────────
    tflite::InitializeTarget();

    tfl_model = tflite::GetModel(gesture_model_tflite);
    if (tfl_model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("ERROR: Model schema version mismatch!"); while (1);
    }

    static tflite::AllOpsResolver resolver;
    static tflite::MicroInterpreter static_interpreter(
        tfl_model, resolver, tensor_arena, kTensorArenaSize);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println("ERROR: AllocateTensors() failed — try increasing kTensorArenaSize");
        while (1);
    }

    tfl_input  = interpreter->input(0);
    tfl_output = interpreter->output(0);

    // Print tensor info to help with debugging
    Serial.print("Input  shape : ");
    Serial.print(tfl_input->dims->data[1]); Serial.print("x");
    Serial.println(tfl_input->dims->data[2]);
    Serial.print("Input  scale / zero_point : ");
    Serial.print(tfl_input->params.scale, 6); Serial.print(" / ");
    Serial.println(tfl_input->params.zero_point);
    Serial.print("Output scale / zero_point : ");
    Serial.print(tfl_output->params.scale, 6); Serial.print(" / ");
    Serial.println(tfl_output->params.zero_point);

    Serial.println("\nReady. Send 'c' to capture and classify.");
}

// ── loop ──────────────────────────────────────────────────────────────────────

void loop() {
    if (!Serial.available()) return;
    char cmd = Serial.read();
    if (cmd != 'c') return;

    Serial.println("\nCapturing...");
    captureAndFillTensor();

    Serial.println("Running inference...");
    if (interpreter->Invoke() != kTfLiteOk) {
        Serial.println("ERROR: Invoke() failed!"); return;
    }

    // Dequantise output scores and find the best class
    float   out_scale = tfl_output->params.scale;
    int32_t out_zp    = tfl_output->params.zero_point;

    int   best_idx   = 0;
    float best_score = -1.0f;

    Serial.println("Scores:");
    for (int i = 0; i < NUM_CLASSES; i++) {
        float score = (tfl_output->data.int8[i] - out_zp) * out_scale;
        if (score < 0.0f) score = 0.0f;
        Serial.print("  ");
        Serial.print(CLASS_NAMES[i]);
        Serial.print(": ");
        Serial.println(score, 4);
        if (score > best_score) {
            best_score = score;
            best_idx   = i;
        }
    }

    Serial.println();
    if (best_score >= CONFIDENCE_THRESHOLD) {
        Serial.print("GESTURE DETECTED: ");
        Serial.print(CLASS_NAMES[best_idx]);
        Serial.print("  (");
        Serial.print((int)(best_score * 100));
        Serial.println("%)");
    } else {
        Serial.print("NO GESTURE DETECTED");
        Serial.print("  (best: ");
        Serial.print(CLASS_NAMES[best_idx]);
        Serial.print(" @ ");
        Serial.print((int)(best_score * 100));
        Serial.println("%)");
    }

    // ── Optional: dump grayscale debug image over Serial ─────────────────────
    // Uncomment this block and pipe the serial output into the Python script
    // below to visualise what the camera saw after downsampling.
    //
    // Python one-liner to visualise (run on host while monitor is open):
    //   python3 -c "
    //   import serial, numpy as np, matplotlib.pyplot as plt
    //   s = serial.Serial('/dev/ttyACM0', 115200)
    //   while True:
    //       line = s.readline().decode().strip()
    //       if line == 'DEBUG_IMAGE_START': break
    //   rows = []
    //   for _ in range(96):
    //       rows.append([int(x, 16) for x in s.readline().decode().split()])
    //   plt.imshow(np.array(rows), cmap='gray', vmin=0, vmax=255); plt.show()
    //   "
    /*
    Serial.println("\nDEBUG_IMAGE_START");
    for (int i = 0; i < IMG_ROWS * IMG_COLS; i++) {
        if (debug_image[i] < 16) Serial.print("0");
        Serial.print(debug_image[i], HEX);
        if ((i + 1) % IMG_COLS == 0) Serial.println();
        else Serial.print(" ");
    }
    Serial.println("DEBUG_IMAGE_END\n");
    */
}