"""
TFLite to C Header File Converter
Author: CST-440 Team
Date: January 15, 2026

Converts a TensorFlow Lite model (.tflite) to a C header file (.h)
for embedding in Arduino or other embedded systems.

Usage:
    python convert_tflite_to_c.py trig_model_int8.tflite

    # Custom output file
    python convert_tflite_to_c.py trig_model_int8.tflite -o model_data.h

    # Custom variable name
    python convert_tflite_to_c.py trig_model_int8.tflite -n my_model
"""

import argparse
import os
import sys


def convert_tflite_to_c_header(tflite_path, output_path=None, var_name=None):
    """
    Convert a TFLite model to a C header file.

    Args:
        tflite_path: Path to input .tflite file
        output_path: Path to output .h file (optional)
        var_name: Variable name for the array (optional)
    """

    # Validate input file
    if not os.path.exists(tflite_path):
        print(f"Error: File not found: {tflite_path}")
        sys.exit(1)

    if not tflite_path.endswith('.tflite'):
        print(f"Warning: Input file doesn't have .tflite extension")

    # Generate output path if not provided
    if output_path is None:
        base_name = os.path.splitext(os.path.basename(tflite_path))[0]
        output_path = f"{base_name}_data.h"

    # Generate variable name if not provided
    if var_name is None:
        base_name = os.path.splitext(os.path.basename(tflite_path))[0]
        # Convert to valid C identifier (replace invalid chars with underscores)
        var_name = base_name.replace('-', '_').replace('.', '_')

    print(f"{'='*70}")
    print("TFLite to C Header Converter")
    print(f"{'='*70}")
    print(f"Input file:     {tflite_path}")
    print(f"Output file:    {output_path}")
    print(f"Variable name:  {var_name}")
    print()

    # Read the TFLite model as binary
    try:
        with open(tflite_path, 'rb') as f:
            tflite_data = f.read()
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

    model_size = len(tflite_data)
    print(f"Model size: {model_size:,} bytes ({model_size/1024:.2f} KB)")

    # Generate C header file
    try:
        with open(output_path, 'w') as f:
            # Write header guard and comments
            guard_name = f"{var_name.upper()}_H"

            f.write(f"// Auto-generated C header file for TensorFlow Lite model\n")
            f.write(f"// Source: {os.path.basename(tflite_path)}\n")
            f.write(f"// Model size: {model_size:,} bytes ({model_size/1024:.2f} KB)\n")
            f.write(f"// Generated by convert_tflite_to_c.py\n")
            f.write(f"\n")
            f.write(f"#ifndef {guard_name}\n")
            f.write(f"#define {guard_name}\n")
            f.write(f"\n")

            # Write the array declaration
            f.write(f"// TensorFlow Lite model data\n")
            f.write(f"alignas(8) const unsigned char {var_name}_tflite[] = {{\n")

            # Write bytes in rows of 12 for readability
            bytes_per_row = 12
            for i in range(0, len(tflite_data), bytes_per_row):
                row_data = tflite_data[i:i+bytes_per_row]
                hex_values = ', '.join(f'0x{byte:02x}' for byte in row_data)

                # Add comma unless it's the last row
                if i + bytes_per_row < len(tflite_data):
                    f.write(f"  {hex_values},\n")
                else:
                    f.write(f"  {hex_values}\n")

            f.write(f"}};\n")
            f.write(f"\n")

            # Write the length constant
            f.write(f"// Model size in bytes\n")
            f.write(f"const unsigned int {var_name}_tflite_len = {model_size};\n")
            f.write(f"\n")
            f.write(f"#endif  // {guard_name}\n")

        print(f"\n✓ Successfully converted to C header file!")
        print(f"✓ Saved to: {output_path}")
        print()
        print(f"To use in Arduino:")
        print(f"1. Copy {output_path} to your Arduino sketch folder")
        print(f"2. In your .ino file, add:")
        print(f"   #include \"{os.path.basename(output_path)}\"")
        print(f"3. Access the model data with:")
        print(f"   {var_name}_tflite        (pointer to byte array)")
        print(f"   {var_name}_tflite_len    (size in bytes)")
        print()

    except Exception as e:
        print(f"Error writing output file: {e}")
        sys.exit(1)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Convert TFLite model to C header file for Arduino/embedded systems',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python convert_tflite_to_c.py trig_model_int8.tflite
  python convert_tflite_to_c.py model.tflite -o my_model.h
  python convert_tflite_to_c.py model.tflite -n custom_name
        """
    )

    parser.add_argument('input', help='Input TFLite model file (.tflite)')
    parser.add_argument('-o', '--output', help='Output C header file (.h)')
    parser.add_argument('-n', '--name', help='Variable name for the array')

    args = parser.parse_args()

    convert_tflite_to_c_header(args.input, args.output, args.name)

    return 0


if __name__ == "__main__":
    sys.exit(main())